name: Action workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Javascript Action
        id: hello
        uses: actions/hello-world-javascript@1
        with: 
          who-to-greet: devopshint
      - name: get the output line
        run: echo "${{ steps.hello.output.time }}"